name: Github Actions Practica

on: [push]

jobs:
  explorando-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar evento
        run: |
          echo "El flujo de trabajo ha sido ejecutado en el evento: ${{ github.event_name }}"

      - name: Mostrar sistema operativo
        run: |
          echo "El trabajo se esta ejecutando en un servidor ${{ runner.os }} hospedado en GitHub"

      - name: Mostrar rama y repositorio
        run: |
          echo "El nombre de la rama es: ${{ github.ref }} y tu repositorio es: ${{ github.repository }}."

      - name: Verifica el codigo del repositorio
        uses: actions/checkout@v2

      - name: Mensaje repositorio listo
        run: |
          echo "El repositorio: ${{ github.repository }} ha sido colocado al runner."

      - name: Mensaje listo para verificar
        run: |
          echo "El flujo de trabajo esta listo para verificar el codigo en el runner."

      - name: Listar archivos en el repositorio
        run: |
          ls ${{ github.workspace }}

      - name: Mostrar estado del trabajo
        run: |
          echo "El estado del trabajo es: ${{ job.status }}."

      - name: Hola
        run: echo "Hola"
